apiVersion: v1
kind: Template
metadata:
  name: sentry-postgres-secrets
  annotations:
    description: Secrets for Sentry's PosgreSQL
    version: 0.0.1
    tags: poc,sentry
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
  labels:
    app: sentry
    template: sentry-postgres-secrets
    component: postgres

objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: sentry-postgres
      labels:
        app: sentry
        component: postgres
    stringData:
      POSTGRESQL_PASSWORD: "${POSTGRESQL_PASSWORD}"
      POSTGRESQL_USER: postgres
      POSTGRESQL_DATABASE: sentry

parameters:
- description: Password used for PostgreSQL
  from: '[a-zA-Z0-9]{25}'
  generate: expression
  name: POSTGRESQL_PASSWORD
  required: true
