apiVersion: v1
kind: Template
metadata:
  name: sentry-redis-secrets
  annotations:
    description: Secrets for Sentry's Redis
    version: 0.0.1
    tags: poc,sentry
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
  labels:
    app: sentry
    template: sentry-redis-secrets
    component: redis

objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: sentry-redis
      labels:
        app: sentry
        component: redis
    stringData:
      SENTRY_REDIS_HOST: "${SENTRY_REDIS_HOST}"
      SENTRY_REDIS_PORT: "${SENTRY_REDIS_PORT}"
      SENTRY_REDIS_PASSWORD: "${SENTRY_REDIS_PASSWORD}"
      SENTRY_REDIS_DB: "${SENTRY_REDIS_DB}"

parameters:
- description: A host where Redis instance sits
  displayName: Redis Host
  name: SENTRY_REDIS_HOST
  required: true
  value: redis

- description: A port where Redis instance sits
  displayName: Redis Port
  name: SENTRY_REDIS_PORT
  required: true
  value: '6379'

- description: Redis Database Password
  displayName: Redis Database Password
  name: SENTRY_REDIS_PASSWORD
  required: false
  value: ''

- description: Redis Database Name
  displayName: Redis Database Name
  name: SENTRY_REDIS_DB
  required: true
  value: '0'